[package]
name = "unsophisticated-lang"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "unsoph-repl"
path = "src/bin/repl.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.*"
